name: openfe_env
channels:
  - conda-forge
dependencies:
  - cudatoolkit==11.8
  - jupyterlab
  - notebook
  - openfe
  - pip
  - py3dmol
  - pytest
  - pytest-xdist
  - python==3.12.*
  - rdkit==2025.09.1
